config/routes.rb
Rails.application.routes.draw do
  resources :breeds

  root "breeds#index"

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breed = DogBreedFetcher.fetch
  end

  def show
    @breed = Breed.find(params[:id])
  end

  def create
    breed = DogBreedFetcher.fetch(params[:breed_name])
    redirect_to breed_path(breed.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
  def breed_options_for_select
    DogBreedNameList
      .fetch
      .map { |name| [name, name] }
  end
end

app/views/breeds/index.html.erb
<div class="dog">

  <h1>It's a dog</h1>

  <h3><%= @breed.name.humanize %></h3>

  <%= image_tag @breed.pic_url %>

  <h2>Select a breed</h2>
  <%= form_tag breeds_path do %>
    <%= select_tag "breed_name", options_for_select(breed_options_for_select),
      id: "breed_name",
      onchange: "this.form.submit();"
    %>
  <% end %>

</div>

app/views/breeds/show.html.erb
<div class="dog">

  <h1>It's a dog</h1>

  <h3><%= @breed.name.humanize %></h3>

  <%= image_tag @breed.pic_url %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>